# Generated by Django 5.1.6 on 2025-03-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sk_python_project', '0004_remove_entry_owner_topic_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
