# Generated by Django 5.1.6 on 2025-04-07 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sk_python_project', '0007_notification'),
    ]

    operations = [
    ]
