# Generated by Django 5.1.6 on 2025-04-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sk_python_project', '0009_alter_notification_options_remove_notification_entry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='action',
            field=models.CharField(default='acted', max_length=20),
        ),
    ]
