# Generated by Django 5.1.6 on 2025-04-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sk_python_project', '0010_alter_notification_action'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'permissions': [('can_delete_any_entry', 'Can delete any entry'), ('can_edit_any_entry', 'Can edit any entry')], 'verbose_name_plural': 'entries'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'permissions': [('can_delete_any_topic', 'Can delete any topic'), ('can_view_all_topics', 'Can view all topics (including private)'), ('can_edit_any_topic', 'Can edit any topic')]},
        ),
        migrations.AddField(
            model_name='topic',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image for this topic', null=True, upload_to='topic_images/'),
        ),
    ]
