# Generated by Django 5.1.6 on 2025-04-22 18:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sk_python_project', '0011_alter_entry_options_alter_topic_options_topic_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='video',
            field=models.FileField(blank=True, help_text='Upload a video for this topic', null=True, upload_to='topic_videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi', 'webm'])]),
        ),
    ]
